---
abstract: 'Capture callstacks for later presentation.'
author:
  - 'Paul Liebert <paull@peak.org>'
build_requires:
  Test::Exception: 0.32
  Test::More: 1.001
configure_requires:
  ExtUtils::MakeMaker: 7.00
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Capture
no_index:
  directory:
    - t
    - inc
requires:
  Carp::Proxy: 0.12
  English: 1.06
  Moose: 2.1005
  Readonly: 1.04
  perl: 5.01
  warnings: 1.18
version: 0.02
